### ISSUE TITLE
Arrumar um tema

### ISSUE THREAD

**Issue by fpg1503** [OlimpiadasCientificas/olimpiadascientificas.github.io#1]
Precisamos de um tema para Jekyll bonitinho

**Comment by itf** [comment]
Algum tema como esse? http://jekyllthemes.org/themes/jasper/

**Comment by fpg1503** [comment]
Esse tema é bem bonito e limpo a gente só tem que pensar se num é uma mudança muito grande da cara que o OC teve até hoje. Talvez esteja na hora de mudar radicalmente mas provavelmente é melhor colocar elementos que remetam o lavout antigo, não? Tenho um pouco de medo dos usuários não conseguirem achar o menu na lateral.

**Comment by itf** [comment]
http://jekyllthemes.org/themes/fengzhichu-theme/?

**Comment by itf** [comment]
Que tal deixar os temas de lado e fazer tudo pouco a pouco mudando o css?
