### ISSUE TITLE
Migrar posts do OC

### ISSUE THREAD

**Issue by fpg1503** [OlimpiadasCientificas/olimpiadascientificas.github.io#2]

**Comment by itf** [comment]
Que tal primeiro recuperar os posts e páginas com aquele script automático e depois tentar achar um tema que funcione?

**Comment by fpg1503** [comment]
Beleza, vou fazer um dump do DB para minha máquina, rodar o script localmente e ver o que dá.

**Comment by itf** [comment]
Como posso ajudar?

**Comment by fpg1503** [comment]
Então, o problema é que os links não funcionam, eu subi como está o resultado final na branch `importer` e vou te mandar o SQL por e-mail (ele pode ter algum dado sensível de usuários)

**Comment by itf** [comment]
ok!

**Comment by itf** [comment]
Acho melhor jogarmos todos os posts foras. O NOIC tem side um bom canal de notícias, a gente pode ficar postando os resultado depois, e só ter as competições nacionais em um calendário. 

Eu consegui consertar os links, o maior problema era que alguns caracterses estavam sendo substituidos (escaped) de maneira inconsistente.
