### ISSUE TITLE
Consertar imagens

### ISSUE THREAD

**Issue by itf** [OlimpiadasCientificas/olimpiadascientificas.github.io#7]
Fazer com que as imagens das páginas redirecionem para coisas no github, em vez de no site original

**Comment by joaofreires** [comment]
Você pode pegar pelo
raw.githubusercontent.com/<USER>/<REPOSITORIO>/<BRANCH>/<PATH_TO_FILE>

por exemplo:
https://raw.githubusercontent.com/OlimpiadasCientificas/olimpiadascientificas.github.io/master/static/fotos/GEDC0019_1.jpg

**Comment by itf** [comment]
Completado! Modifiquei todas as páginas de olimpíadas para usarem markdown e arrumei as imagens.
